In [32]:
import numpy as np
def activition_function(vector, activation_func:str):
    if activation_func == "ReLU":
        #loops through elements in vector to see the maximum btw the element and 0
        g_x = np.maximum(vector, 0)
        
    elif activation_func == "sigmoid":
        g_x = 1/(1 + np.exp(-vector))
    return g_x

In [34]:
# vectors between 1 to 10 of size n
n = 10
vector = np.random.randint(-10, 11, size=n)

activition_function(vector, "sigmoid")

array([3.35350130e-04, 4.74258732e-02, 9.99954602e-01, 9.99876605e-01,
       9.11051194e-04, 1.19202922e-01, 8.80797078e-01, 4.53978687e-05,
       3.35350130e-04, 9.11051194e-04])

In [20]:
np.maximum(vector, 0)

array([0, 2, 6, 0, 6, 0, 5, 7, 0, 4])

In [21]:
np.max(vector)

7

In [22]:
vector

array([-7,  2,  6, -5,  6, -2,  5,  7, -6,  4])

In [24]:
1/(1 + np.exp(-vector))

array([9.99088949e-01, 1.19202922e-01, 2.47262316e-03, 9.93307149e-01,
       2.47262316e-03, 8.80797078e-01, 6.69285092e-03, 9.11051194e-04,
       9.97527377e-01, 1.79862100e-02])